import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Al-Quran Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Al-Quran Assesment</h1>

        <p className={styles.description}>
          Powered with{" "}
          <a href="https://github.com/penggguna/QuranJSON" className={styles.code}>
            QuranJSON
          </a>{" "}
          by{" "}
          <a href="https://github.com/penggguna" className={styles.code}>
            penggguna
          </a>
        </p>

        <div className={styles.grid}>
          <Link href="/question/1">
            <a className={styles.card}>
              <h2>Start &rarr;</h2>
              <p>Start the assessment!</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Copyright 2021 Al-Quran Assessment
        </a>
      </footer>
    </div>
  );
}
